audit_header: false
title: Phoenix Real Estate Video Blog with Kodi Riddle
description: >-
  Our mission at Riddle Realty is to be your best resource for Phoenix real
  estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The Riddle Realty, your professional
  Phoenix Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /testimonials/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Kodi Riddle
  title:
  license_number:
  about_markdown: >
    When you are buying or selling property in today's real estate market, it's
    important to have confidence in your real estate professional. My commitment
    as your local REALTOR® is to provide you with the specialized real estate
    service you deserve.


    When you are an informed buyer or seller, you'll make the best decisions for
    the most important purchase or sale in your lifetime. That's why my goal is
    to keep you informed on trends in the marketplace using the latest
    statistics in your local area. With property values continuing to rise, real
    estate is a sound investment for now and for the future.


    As a local area expert with knowledge of the communities, my objective is to
    work diligently to assist you in meeting your real estate goals.


    If you are considering buying or selling a home or would just like to have
    additional information about real estate in your area, please don't hesitate
    to call or e-mail me.
  brand: Riddle Realty
  brokerage:
  market: Phoenix
  address: '4524 E. Rancho Laredo Dr.<br>Cave Creek, AZ 85331'
  phone: 480-502-0505
  phone_type:
  phone2:
  phone2_type:
  email: Kodi@RiddleRealty.com
  url: 'https://www.thekodiriddleteam.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: >-
    http://www.searchallproperties.com/propertyvaluation-plus/billriddle/Phoenix-375819
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.greaterphoenixarearealestate.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Phoenix Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: >-
      http://www.searchallproperties.com/propertyvaluation-plus/billriddle/Phoenix-375819
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Phoenix Home?
    CTA_text2: Search the entire MLS for your Phoenix home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'http://www.greaterphoenixarearealestate.com/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/pages/Cave-Creek-Real-Estate/213551488672346'
  linkedin_url: 'https://www.linkedin.com/in/kodiriddle'
  youtube_url: 'http://www.youtube.com/channel/UCnqI3B314xWogA6C59nGVPQ'
  twitter_url: 'https://twitter.com/KodiRiddle'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Kodi-Riddle/'
  trulia_url: 'http://www.trulia.com/profile/kodi-k-riddle-broker-cave-creek-az-2702865'
  yelp_url:
  podcast_url: >-
    https://itunes.apple.com/us/podcast/greater-scottsdale-area-real/id1071467488?mt=2
podcast:
  title: Phoenix Real Estate Podcast with Kodi Riddle
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Phoenix
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Riddle Realty - your professional
    Phoenix Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Phoenix, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Kodi Riddle
images:
  client_headshot_path: /uploads/kodi-riddle-updated-headshot-1.png
  hero_logo_path: /uploads/logo-kodi-riddle.png
  logo_width_number: 30
  hero_text: Phoenix Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#d80716'
  theme_color: '#36363d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'